// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.b1adf3e7-1c09-43d2-a808-245d7ef68309";
        public const string Name = "VSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "andre";
        public const string Tags = "";
    }
}
