// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "MSExtension.b1adf3e7-1c09-43d2-a808-245d7ef68309";
        public const string Name = "MSExtension";
        public const string Description = @"MSExtension Project.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "andre";
        public const string Tags = "";
    }
}
